name: Build docker and publish

on:
  release:
    types:
      - created


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: build  and push the image
        run: docker buildx build --tag ${{ secrets.DOCKERHUB_USERNAME }}/aax-to-mp3-web-converter:latest --tag ${{ secrets.DOCKERHUB_USERNAME }}/aax-to-mp3-web-converter:${{ steps.get_version.outputs.VERSION }} --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x .
